// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-d2UW6JS_0DWsPu83ppcSsuteIAxe_4E',
    appId: '1:61461520825:web:53812d37e27cb920755668',
    messagingSenderId: '61461520825',
    projectId: 'lawyerapp-8d985',
    authDomain: 'lawyerapp-8d985.firebaseapp.com',
    storageBucket: 'lawyerapp-8d985.appspot.com',
    measurementId: 'G-WBM368QEXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyq8uTq2xmGJ5SOpg7FMMbgpZJLynbYBw',
    appId: '1:61461520825:android:684057b34c731c76755668',
    messagingSenderId: '61461520825',
    projectId: 'lawyerapp-8d985',
    storageBucket: 'lawyerapp-8d985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwAtUFxWlRQWLg_TRJvZLGP1F-XKtgvQg',
    appId: '1:61461520825:ios:3b7fc9f5d5501672755668',
    messagingSenderId: '61461520825',
    projectId: 'lawyerapp-8d985',
    storageBucket: 'lawyerapp-8d985.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwAtUFxWlRQWLg_TRJvZLGP1F-XKtgvQg',
    appId: '1:61461520825:ios:3b7fc9f5d5501672755668',
    messagingSenderId: '61461520825',
    projectId: 'lawyerapp-8d985',
    storageBucket: 'lawyerapp-8d985.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-d2UW6JS_0DWsPu83ppcSsuteIAxe_4E',
    appId: '1:61461520825:web:a13777475c52150b755668',
    messagingSenderId: '61461520825',
    projectId: 'lawyerapp-8d985',
    authDomain: 'lawyerapp-8d985.firebaseapp.com',
    storageBucket: 'lawyerapp-8d985.appspot.com',
    measurementId: 'G-R1ZMPYFE92',
  );

}